name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'

jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
            name: Checkout main repository

          - name: Checkout submodules with SSL verification bypassed
            run: |
              # Disable SSL verification temporarily to bypass certificate errors
              export GIT_SSL_NO_VERIFY=true
              git submodule update --init --recursive

          - uses: webfactory/ssh-agent@v0.5.3
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh

          - name: Cleanup
            if: always()
            run: |
              # Ensure SSH agent is running and then remove all identities
              eval $(ssh-agent -s)  # Start the SSH agent if it's not already running
              ssh-add -D  # Remove all identities from the SSH agent
