name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
            name: Checkout main repository
          
          - name: Install wget and CA certificates
            run: |
              # Install wget and the ca-certificates package
              apt-get update && apt-get install -y wget ca-certificates
              # Rehash the certificates
              update-ca-certificates

          - name: Checkout submodules
            run: git submodule update --init --recursive
          
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Download Buildroot Certificate using wget
            run: |
              # Download the certificate using wget
              wget --no-check-certificate https://git.busybox.net/buildroot/

          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh

          - name: Cleanup
            if: always()
            run: |
              # Ensure SSH agent is running and then remove all identities
              eval $(ssh-agent -s)  # Start the SSH agent if it's not already running
              ssh-add -D  # Remove all identities from the SSH agent
